# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz

stage: Comprehensive tests

stages:
   # Do the style check and a single test job, don't proceed if it fails
   - name: Initial tests
   # Test docs, astropy dev, and without optional dependencies
   - name: Comprehensive tests
   # Leaving windows to the last stage
   - name: Windows test
   # These will only run when cron is opted in
   - name: Cron tests
     if: type = cron

env:
    global:

        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.8
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - PIP_DEPENDENCIES='pytest-astropy requests mimeparse requests_mock'
        - EVENT_TYPE='pull_request push'
        - CONDA_CHANNELS='astropy'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Make sure that egg_info works without dependencies
        - env: SETUP_CMD='egg_info'
          stage: Initial tests

        # Do a PEP8 test with flake8
        - os: linux
          stage: Initial tests
          env: MAIN_CMD='flake8' SETUP_CMD=''

        # Do a coverage test.
        - os: linux
          stage: Initial tests
          env: PYTHON_VERSION=3.8 SETUP_CMD='test --coverage'

        # Now try Astropy dev and LTS vesions with the latest 3.x.
        - os: linux
          env: ASTROPY_VERSION=development
               EVENT_TYPE='pull_request push cron'
          stage: Comprehensive tests
        - os: linux
          env: ASTROPY_VERSION=lts
          stage: Comprehensive tests

          # try all python versions
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.15 ASTROPY_VERSION=3.2
               PIP_DEPENDENCIES='requests mimeparse requests_mock contextlib2'
          stage: Comprehensive tests

        - os: linux
          env: PYTHON_VERSION=3.7
          stage: Comprehensive tests

        # Check for sphinx doc build warnings
        - os: linux
          env: PYTHON_VERSION=3.7 SETUP_CMD='build_docs -w'
               PIP_DEPENDENCIES='requests mimeparse requests_mock sphinx_astropy'
          stage: Comprehensive tests

        # Try MacOS X
        - os: osx
          stage: Cron tests
          env: SETUP_CMD='test'


        # Try on windows. Since it takes longer, only run after everything passes
        - os: windows
          stage: Windows test


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
          codecov;
      fi
